drivers/classic/src/vic_classic.c, drivers/image/src/vic_start.c, drivers/shared/include/vic_driver_shared.h, drivers/shared/src/get_parameters.c
- Not all parameters are validated (more checks could be added)
- Function is called regardless of the presence of the parameter input file so default parameters are checked during each run time.
- Works for both image and classic drivers
closes #189.
=> Added function to validate model parameters

vic_run/include/vic_log.h
`log_ncerr` now looks up the error message string and prints it, along with the file and line number.
=> fix log_ncerr macro

vic_run/include/vic_log.h
Change the log_warn macro to reset the error message after warning (not sure this is entirely safe). If not, old error messages keep being repeated
=> Reset the error message to 0 after warning (if not it will get repeated)

tests/run_tests.py, vic/drivers/classic/Makefile, vic/drivers/image/Makefile, vic/vic_run/include/vic_log.h
This PR allows for the compile time setting of the logging level in VIC. Level options are:
| Level     | Numeric value    |
|---------  |---------------   |
| ERROR     | 40               | 
| WARNING   | 30               |
| INFO      | 20               |
| DEBUG     | 10               |
| NOTSET    | 0                |
These options match those in the [Python logging module](https://docs.python.org/2/library/logging.html#logging-levels).
To turn off `DEBUG` logging, the user sets `LOG_LVL > 10`.  This PR does not allow turning off the Error level logging and will raise an error during compilation.
closes #218
=> Set log level at compile time

CONTRIBUTING.md, ChangeLog, readme.md
This branch resolves a few merge conflicts that have piled up while we've been working on VIC.5.  Because I have been manually porting changes to the develop branch all along, the merge was done using the "ours" rule: `VIC (feature/resolve_master_merge_conflicts)$ git merge upstream/master --strategy-option ours`.
This will allow us to merge the docs into `develop` here shortly as well as merge `develop` back into `master` when 5.0 is ready to release.
There were no code changes here so we can merge this as soon as the travis build passes.
=> resolve master merge conflicts

vic/drivers/python/setup.py
This allows us to control the logging in the python driver from setup.py.  It is currently set low (0), since all we do with the python driver is unit tests and py.test filters standard out if an exception isn't raised.
=> set log level in setup.py

tools/code_format/run_uncrustify.bash, vic/drivers/classic/src/initialize_atmos.c, vic/drivers/image/src/vic_image.c, vic/drivers/image/src/vic_init_output.c, vic/drivers/image/src/vic_mpi_support.c, vic/vic_run/include/vic_def.h, vic/vic_run/src/interpoloation.c
Uncrustify was missed on a few recent PRs.  This fixes a few lines and updates the helper script to include the new VIC source file paths.
=> Run uncrustify over all sources

vic/vic_run/include/vic_def.h
The curse of the dreaded PET code! 
This fixes build in classic and cesm drivers.  @bartnijssen - do you remember why these vars were set to zero?
=> fix zero dim array error raised by PGI compilers

tests/unit/vic_run/test_comparisons.py, vic/drivers/python/vic_headers.py, vic/vic_run/include/vic_run.h, vic/vic_run/src/comparisons.c
This PR adds a few simple floating point comparison functions, something VIC is desperately in need of. Lines like [this one](https://github.com/UW-Hydro/VIC/blob/develop/vic/drivers/image/src/vic_init.c#L1054) are all over the VIC code base.
I included unit tests for both comparisons but did not go hunting in the code for oportunities to apply the functions, that is for a later date.
If we feel it is necessary, I can add more robust comparisons such as:
- http://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.testing.assert_array_almost_equal_nulp.html#numpy.testing.assert_array_almost_equal_nulp
- http://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.testing.assert_array_max_ulp.html#numpy.testing.assert_array_max_ulp
or relative greater/less or equal to comparisons. …
=> add comparisons module

vic/drivers/shared/include/vic_driver_shared.h
Changed the size of char `varname[20];` to `char varname[30];` in `vic_driver_shared.h`. This has to be done because some strings in `output_list_utils.c` are longer than 20 and this will cause buffer overflows.
=> buffer overflow fix

src/arno_evap.c, src/calc_veg_params.c, src/full_energy.c, src/func_surf_energy_bal.c, src/vicNl_def.h
I had intended to add this update to the original 4.2 release, but forgot about it until now.  This addresses issue #306.
=> Update to code for Esoil in sparse vegetation.

docs/Documentation/VICDisagg.md, src/check_files.c, src/initialize_atmos.c, src/vicNl.c
This addresses the requirement that initialize_atmos() have information about the number of veg tiles in the grid cell to know how to read the forcing files (if they contain timeseries of LAI, vegcover, or albedo).  Previously VIC wasn't reading the veg lib/param files when in OUTPUT_FORCE mode, which resulted in segmentation faults when trying to access veg_lib or veg_param data structures.  Now VIC reads those files even in OUTPUT_FORCE mode.
This addresses issue #305.
=> Fix OUTPUT_FORCE option.

vic/drivers/image/include/vic_driver_image.h, vic/drivers/image/src/get_global_domain.c, vic/drivers/image/src/print_library_image.c, vic/drivers/image/src/vic_alloc.c, vic/drivers/image/src/vic_finalize.c, vic/drivers/image/src/vic_force.c, vic/drivers/image/src/vic_image.c, vic/drivers/image/src/vic_image_run.c, vic/drivers/image/src/vic_init.c, vic/drivers/image/src/vic_init_output.c, vic/drivers/image/src/vic_mpi_support.c, vic/drivers/image/src/vic_restore.c, vic/drivers/image/src/vic_start.c, vic/drivers/image/src/vic_store.c, vic/drivers/image/src/vic_write.c, vic/vic_run/src/CalcBlowingSnow.c, vic/vic_run/src/lakes.eb.c, vic/vic_run/src/photosynth.c, vic/vic_run/src/root_brent.c
Added a `run` member to the locations struct.
During domain composition, only the active gridcells are stored in the local domain structs.
See issue: #313
" @wietsefranssen and @jhamman have been discussing how to get all the domain information into the output files. It seems like it will be best to store all grid cells (active and not) in the global domain and then, during the domain decomposition, only store the active grid cells. An run member will be added to the domain structure.
"
=> Added all grid cells to global domain structure.

docs/Development/ReleaseNotes.md
Pretty self-explanatory if you look at the code changes.  Only affects docs/Development/ReleaseNotes.md.
closes #351
=> Added description of updates contained in release 4.2.c to the 5.0 documentation.

samples/global.param.sample.image.txt, tests/unit/shared/test_vic_time.py, vic/drivers/classic/src/get_global_param.c, vic/drivers/image/include/vic_driver_image.h, vic/drivers/image/include/vic_mpi.h, vic/drivers/image/src/get_global_param.c, vic/drivers/image/src/get_nc_var_attr.c, vic/drivers/image/src/vic_force.c, vic/drivers/image/src/vic_init.c, vic/drivers/python/vic_headers.py, vic/drivers/shared/include/vic_driver_shared.h, vic/drivers/shared/src/vic_time.c
This PR cleans up the image driver global parameter file and deprecates invalid or unnecessary options. A follow up PR will have to add functionality to the selection of forcing files.
TODO:
closes #373
=> deprecate options in image driver.

docs/Development/ReleaseNotes.md, docs/Documentation/Drivers/Classic/ForcingData.md, docs/Documentation/OutputVarList.md, samples/global.param.sample.image.txt, vic/drivers/classic/include/vic_driver_classic.h, vic/drivers/classic/src/parse_output_info.c, vic/drivers/classic/src/set_output_defaults.c, vic/drivers/classic/src/vic_force.c, vic/drivers/classic/src/write_forcing_file.c, vic/drivers/image/include/vic_driver_image.h, vic/drivers/image/src/get_global_domain.c, vic/drivers/image/src/get_global_param.c, vic/drivers/image/src/get_nc_var_attr.c, vic/drivers/image/src/set_force_type.c, vic/drivers/image/src/vic_alloc.c, vic/drivers/image/src/vic_force.c, vic/drivers/image/src/vic_init_output.c, vic/drivers/image/src/vic_nc_info.c, vic/drivers/image/src/vic_start.c, vic/drivers/python/vic_headers.py, vic/drivers/shared/include/vic_driver_shared.h, vic/drivers/shared/src/forcing_utils.c, vic/drivers/shared/src/output_list_utils.c, vic/drivers/shared/src/put_data.c, vic/vic_run/include/vic_def.h
This PR closes #211.  Forcing variables can be specified in the global parameter following the convention proposed in #211.
~~blocked by #378~~
=> specify netcdf variable names in global parameter file

vic/drivers/classic/src/parse_output_info.c, vic/drivers/classic/src/vic_classic.c
When no OUTFILE specified in global file, output default files;
When OUTFILE is specified but no corresponding OUTVAR specified, raise
an error.
=> Fixed output file bugs in classic mode.

src/write_data.c
dmy structure is NULL if OUTPUT_FORCE option is TRUE; thus, dmy->year, etc. cannot be accessed in write_data.c
=> Update write_data.c for binary output when OUTPUT_FORCE=TRUE

docs/Development/ReleaseNotes.md, vic/drivers/classic/src/initialize_model_state.c, vic/drivers/classic/src/read_soilparam.c, vic/drivers/shared_all/src/initialize_lake.c, vic/drivers/shared_image/src/vic_init.c, vic/vic_run/include/vic_run.h, vic/vic_run/src/lakes.eb.c
This fix addresses several minor bugs.  Several lake processes (aerodynamic resistance, albedo, latent/sensible heat fluxes, net radiation, etc) were reported incorrectly or not at all in output files.  The fixes for those were all minor (1-liners).  Lake temperatures were initialized to unrealistic temperatures in the absence of an initial state file.  The fix for that was a little more involved: replaced the use of first step's air temperature with use of annual average soil temperature.
closes #405 
closes #406 
closes #419 
closes #420
=> Miscellaneous lake fixes

vic/drivers/shared_image/src/vic_mpi_support.c
Note that I also changed the order of some of the elements to reflect the order in the data structures. This should not make any difference since we are using offsetof.
For the Stehekin data set this fixed scrambled fields in the output and addresses (at least in part) issues #445 and #449 although the latter should remain open since better validation of the MPI_Datatypes would still be useful.
Stehekin sample data set output with np = 4 from develop for `out_soil_moist`
Stehekin sample data set output with np = 4 with this fix for `out_soil_moist`
=> Updated MPI_Create_xxx() functions to reflect changes in data structures

vic/drivers/classic/include/vic_driver_classic.h, vic/drivers/classic/src/check_state_file.c, vic/drivers/classic/src/open_state_file.c
The binary format state I/O did not run previously, due to inconsistent data type issue. Fixed this bug.
=> Fixed a bug when read/write binary state file

vic/drivers/classic/include/vic_driver_classic.h, vic/drivers/classic/src/free_out_data_files.c, vic/drivers/classic/src/parse_output_info.c, vic/drivers/classic/src/vic_classic.c, vic/drivers/shared_all/include/vic_driver_shared_all.h, vic/drivers/shared_all/src/output_list_utils.c, vic/drivers/shared_image/src/alloc_atmos.c, vic/drivers/shared_image/src/vic_finalize.c, vic/drivers/shared_image/src/vic_init.c
This PR fixes the following memory leaks in VIC 5.0 (from issue #463 ):
Image Driver:
```shell
vic_init.c: 74
alloc_atmos.c: 41, 45
make_veg_var.c: 46
make_snow_data.c: 50
make_cell_data.c: 44
make_energy_bal.c: 49
```
Classic Driver:
```shell
set_output_defaults.c: 94
```
This does not (yet) completely resolve issue #463 but gets us part-way there, anyway.  If preferable, I can keep adding fixes to this PR until they're all fixed.
=> Fixed memory leaks in some functions.

vic/drivers/classic/src/vic_populate_model_state.c, vic/drivers/image/src/vic_image.c, vic/drivers/shared_all/include/vic_driver_shared_all.h, vic/drivers/shared_all/src/initialize_soil.c, vic/drivers/shared_image/include/vic_driver_shared_image.h, vic/drivers/shared_image/src/vic_finalize.c, vic/drivers/shared_image/src/vic_init.c, vic/drivers/shared_image/src/vic_store.c
This PR is to address issue #489 - removed some unused variable warnings in VIC code, including:
- `soil_con` in `initialize_soil()`
- `dmy` in `vic_finalize()`
- `dmy_current` in `vic_store`
=> Removed some unused variables

vic/drivers/image/src/vic_force.c
- In image driver, updated the code so that when the run start time is later than the forcing start time, it skips the correct number of time steps when reading forcing variables
=> Skip correct number of time steps when reading forcing

docs/Development/ReleaseNotes.md, vic/drivers/classic/src/read_initial_model_state.c, vic/drivers/classic/src/write_model_state.c, vic/drivers/image/src/vic_force.c, vic/drivers/shared_all/src/compute_derived_state_vars.c, vic/drivers/shared_image/src/vic_restore.c, vic/drivers/shared_image/src/vic_store.c
This PR assured exact restarts for classic and image driver under simple options (more thorough tests to be done). Specifically:
- Made sure the image driver is doing the same computation as classic driver regarding restarting
- For both drivers, `energy->LongUnderOut` and `energy->snow_flux` are now saved to state file. This is a temporary solution to solving the main points in issue #479 and assuring exact restart.
=> Fixed exact restart (temporarily) - classic and image drivers

vic/drivers/cesm/src/cesm_interface_c.c, vic/drivers/cesm/src/get_global_param.c, vic/drivers/cesm/src/vic_populate_model_state.c, vic/drivers/image/src/vic_image.c, vic/drivers/shared_image/include/vic_driver_shared_image.h, vic/drivers/shared_image/src/vic_store.c
This PR completes the statefile loop in the CESM driver.  Previously, the CESM driver was not reading/writing state files using the [rpointer (restart pointer) system](http://www.cesm.ucar.edu/models/cesm1.0/cice/doc/node28.html) and now it is.  
fixes #461
=> Read/write state and rpointer files in CESM driver

vic/drivers/shared_image/src/vic_finalize.c
little fix: mpi_rank == 0 to mpi_rank == VIC_MPI_ROOT in vic_finalize.c
=> fixed mpi_rank == VIC_MPI_ROOT

vic/drivers/shared_image/src/vic_mpi_support.c
`check_alloc_status(dvar` should be `check_alloc_status(dvar_filtered`. fixed now
=> check_alloc_status

vic/vic_run/include/vic_physical_constants.h, vic/vic_run/src/SnowPackEnergyBalance.c, vic/vic_run/src/calc_surf_energy_bal.c, vic/vic_run/src/func_surf_energy_bal.c, vic/vic_run/src/ice_melt.c, vic/vic_run/src/snow_melt.c
- In vic_run code, fixed bugs that confused volumetric heat capacity
and specific heat capacity related to ice
- We can decide if the value of `CONST_CPICE` (specific heat capacity of ice) is reasonable; but it should not make a huge difference on results
=> Fixed bugs related to ice heat capacity

vic/drivers/classic/src/vic_force.c, vic/drivers/image/src/vic_force.c
- When calculated VPD < 0, now resets VPD to zero, and VP to calculated saturated vapor pressure (this is consistent with VIC4.2)
=> Fixed a bug related to VP - to be consistent with VIC4.2

src/func_canopy_energy_bal.c
- Volumetric heat capacity of water  should be used in `func_canopy_energy_bal.c` instead of specific heat
=> Fixed a bug - volumetric heat capacity of water 

docs/Development/ReleaseNotes.md, vic/vic_run/src/IceEnergyBalance.c, vic/vic_run/src/SnowPackEnergyBalance.c, vic/vic_run/src/func_canopy_energy_bal.c
- Fixed bugs where volumetric heat capacity of water (instead of specific heat) should be used
- **NOTE**: it seems that there is a bug in `VIC4.2` - the hardcoded number `4186.8` here should be volumetric heat of water (which is 4186.8e3):  https://github.com/UW-Hydro/VIC/blob/support/VIC.4.2.d/src/func_canopy_energy_bal.c#L262 . Other places in `VIC4.2` related to volumetric heat of water appear to be correct)
=> Fixed bugs related to volumetric heat capacity of water

vic/drivers/image/src/vic_force.c
This PR changes the units of the VP forcing variable in the image driver to be consistent with the default outputs from VIC.4.2 with `OUTPUT_FORCE == TRUE`
cc @yixinmao - please update the units in the sample dataset.
closes #418
=> Image Driver: SHUM-->VP

vic/drivers/image/src/vic_force.c
Previously, the two drivers require different sets of units for input forcings, which is confusing. Now, the required forcing units for all the 7 required forcing input variables are consistent.
=> Updated vic_force in image driver - now input forcing units are consistent with classic driver

vic/vic_run/include/vic_run.h, vic/vic_run/src/calc_atmos_energy_bal.c, vic/vic_run/src/calc_surf_energy_bal.c, vic/vic_run/src/frozen_soil.c, vic/vic_run/src/ice_melt.c, vic/vic_run/src/root_brent.c, vic/vic_run/src/snow_intercept.c, vic/vic_run/src/snow_melt.c
This silences all warnings about unused `ErrorString` variables.
xref: #581, #526
=> remove all instances of ErrorString

tests/run_profiling.py
example output:
```
----------------- START VIC SCALING PROFILE -----------------
Date                      : 2016-08-27 23:22:59.602087
Machine                   : topaz03.erdc.hpc.mil
User                      : jhamman
VIC Test Git Version      : VIC.5.0.0.rc1-73-g5e21-dirty
VIC Executable            : /p/home/jhamman/VIC/vic/drivers/image/vic_image.exe
VIC Global Parameter File : /p/work2/jhamman/vic5_tests/test1/rasm_vic5_image_test1.global.txt
VIC Executable Version Info
---------------------------
$vic_version
Cores | Time (Seconds)
----------------------
144 | 3463.000000
180 | 2852.000000
108 | 4455.000000
288 | 1996.000000
432 | 1526.000000
216 | 2637.000000
360 | 1739.000000
72 | 6754.000000
864 | 993.000000
36 | 12026.000000
1728 | 726.000000
```
cc @yixinmao for review and …
=> add scaling template for topaz

tests/test_utils.py
Using `matplotlib.use('Agg')` after importing `matplotlib.pyplot` was resulting in this warning message: `UserWarning:  This call to matplotlib.use() has no effect because the backend has already been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot, or matplotlib.backends is imported for the first time.` when running `run_tests.py`. 
This PR fixes this issue.
=> fix user warning in setting plotting backend

vic/drivers/shared_all/src/vic_time.c
Previously NYEARS frequency resulted in `day_in_year = 366` when advance from a leap year to a non-leap year. Fixed this problem by resetting `day_in_year` after advancing year(s).
=> Fixed NYEARS frequency when there are leap years

tests/system/system_tests.cfg, vic/drivers/shared_image/src/vic_restore.c
This PR fixes a problem with image restarts when using multiple processors. Edits were made to the vic_restore.c script to ensure that only the master node validates state file dimensions and coordinate variables. Multiprocessing was also added to a VIC Testing script.
=> Fixing a problem with image restarts when using multiple processors 

docs/Development/ReleaseNotes.md, vic/drivers/shared_all/src/make_dmy.c
When calculating number of steps to skip in the forcing data, should round to integer first before converting to int type to prevent possible 1-timestep wrong offset (due to precision)
=> Fixed a bug when calculating steps of forcing to skip 

docs/Development/ReleaseNotes.md
(Fixing a problem with image restarts when using multiple processors).
=> Added release notes about PR #638.

docs/Development/ReleaseNotes.md, docs/Documentation/Drivers/Image/Domain.md, docs/Documentation/Drivers/Image/GlobalParam.md, docs/Documentation/Drivers/Image/Inputs.md, mkdocs.yml, vic/drivers/shared_image/include/vic_driver_shared_image.h, vic/drivers/shared_image/src/get_global_domain.c, vic/drivers/shared_image/src/get_nc_var_attr.c, vic/drivers/shared_image/src/get_nc_var_type.c
Added check to ensure mask variable in the input domain file is integer type; otherwise raise an error.
=> Added check to ensure mask variable in the input domain file is integer type

vic/drivers/shared_image/src/vic_store.c
2-D lats/lons were being written to state file as fill values rather than actual lats/lons, this PR fixes that.
=> fixed bug in writing statefile for 2-d lat/lon dimensions

docs/Development/ReleaseNotes.md, docs/Documentation/Drivers/Image/StateFile.md, vic/drivers/shared_image/src/vic_restore.c, vic/drivers/shared_image/src/vic_store.c
In image driver, `dz_node` and `node_depth` was assumed to be not spatially-distributed, which was wrong. Now output spatially distributed `dz_node` and `node_depth` in the output state file; also, when reading in an initial state file, check these variables at all grid cells to see if they match the values calculated from soil parameters.
=> Fix dz_node and node_depth in image statefile

docs/Development/ReleaseNotes.md, vic/vic_run/include/vic_run.h, vic/vic_run/src/runoff.c
Drainage from upper layer to adjacent lower layer is calculated by Brook & Corey curve (where drainage rate is a function of upper-layer soil moisture). Before this PR, a simple numerical solution is applied which uses the timestep-beginning upper-layer soil moisture to calculate drainage rate, and assume this constant rate over the entire timestep. This can cause unreasonably large drainage if the curve has a steep shape and when soil moisture is high.
This PR modify layer drainage (Q12) calculation - use exact integral (instead of numerical solution) in order to avoid unreasonably-strong soil moisture oscilation when the Brook & Corey curve is steep.
This PR should close issue #655
=> Improve Q12 calculation

docs/Development/ReleaseNotes.md, vic/drivers/image/src/vic_force.c
Before this bug fix, there would be an error if the simulation start time is later than the forcing start time that year AND the simulation spans multiple years.
=> Fixed a bug - `forceskip` should be reset to zero at the beginning of every year

vic/drivers/cesm/src/cesm_interface_c.c, vic/drivers/image/include/vic_driver_image.h, vic/drivers/image/src/check_save_state_flag.c, vic/drivers/image/src/vic_image.c, vic/drivers/shared_image/include/vic_driver_shared_image.h, vic/drivers/shared_image/src/vic_store.c
In `vic_store()`, we now directly pass in the state time structure (at the state time point) instead of `dmy_current` (which is the beginning of the timestep and one timestep ahead of the state time point). This change will avoid repeatedly advancing one timestep from `dmy_current` in multiple places of the code.
=> Cleaned up vic_store.c the part related to advancing dmy_current for state file timestamp

vic/drivers/image/src/vic_force.c
In PR #671 that fixed bugs to reset `forceskip` to zero at the beginning of every year, there were some parts missing which are addressed in this PR:
- `forceskip` for forcing[1] (the second forcing file, if specified) should also be reset to zero every year
- The check for new year should start from the second timestep (not the third)
=> Fixed some remaining bugs related to reseting forceskip to zero

vic/drivers/image/src/get_global_param.c, vic/drivers/image/src/vic_force.c
Before the fix, "get_global_param" wrongly goes into the if statements to get information for FORCING2, when FORCING2 is not specified.
=> Fixed a bug when checking whether to open the second forcing file in "get_global_param"

docs/Development/ReleaseNotes.md, vic/drivers/cesm/include/vic_driver_cesm.h, vic/drivers/cesm/src/cesm_interface_c.c, vic/drivers/cesm/src/print_library_cesm.c, vic/drivers/cesm/src/vic_cesm_start.c, vic/drivers/cesm/src/vic_cesm_time.c
This PR addresses a conflict that was occurring when compiling a RASM RFR case where two CESM driver functions - `trim` and `advance_time` - were causing conflicts with WRF functions of the same name. I have renamed them as follows: 
- `trim` -> `trimstr`
- `advance_time` -> `advance_vic_time`
=> Feature/fix RASM RFR compiling conflict

docs/Development/ReleaseNotes.md, vic/drivers/image/src/vic_image.c, vic/drivers/shared_all/include/vic_driver_shared_all.h, vic/drivers/shared_image/src/vic_image_timing.c, vic/drivers/shared_image/src/vic_store.c
=> add timers to vic_force and vic_write

tests/test_image_driver.py
This PR enables outputting variable name when comparing variables in a state file for simulations run with different numbers of processors.
=> add variable name for restart test debugging

vic/drivers/cesm/readme.md
This PR updates the readme for the CESM driver to include instructions for the debug flag and currently supported DoD machines.
=> update for debug flag and supported machines

vic/drivers/cesm/src/cesm_put_data.c
This PR updates the comments for vegetation and bare soil albedos in the `cesm_put_data.c` routine. Before this, they were reversed and thus confusing.
=> fixes mistake in comment for veg and bare soil albedos

docs/Development/ReleaseNotes.md, vic/drivers/cesm/include/vic_driver_cesm.h, vic/drivers/cesm/src/cesm_interface_c.c, vic/drivers/cesm/src/cesm_put_data.c, vic/drivers/cesm/src/vic_populate_model_state.c, vic/drivers/classic/include/vic_driver_classic.h, vic/drivers/classic/src/vic_classic.c, vic/drivers/classic/src/vic_populate_model_state.c, vic/drivers/image/include/vic_driver_image.h, vic/drivers/image/src/vic_image.c, vic/drivers/image/src/vic_populate_model_state.c, vic/drivers/shared_all/include/vic_driver_shared_all.h, vic/drivers/shared_all/src/generate_default_state.c, vic/vic_run/include/vic_run.h, vic/vic_run/src/calc_gridcell_avg_albedo.c, vic/vic_run/src/vic_run.c
This quick PR is a follow-up to #712 and #710 so that the `cesm_put_data.c` routine in the CESM driver passes gridcell-averaged albedo to WRF.
=> pass gridcell averaged albedo from all_vars struct to wrf

vic/drivers/shared_all/src/initialize_parameters.c
This PR removes a redundant definition of the frozen soils max iteration number `FROZEN_MAXITER` in `initialize_parameters.c`. (Previously `FROZEN_MAXITER` was defined twice in exactly the same way)
=> remove redundant definition of frozen soils max iteration number

vic/drivers/shared_image/src/vic_store.c
Note: thanks to @itzetoile (Itzel Ruvalcaba) for catching this.
=> Fixed typo in vic_store.c that wrote wrong variable as lake soil T.

docs/Development/ReleaseNotes.md, vic/drivers/cesm/bld/vic.inputfiles.cfg
This PR adds support to the CESM driver for 25km RASM runs with a new set of high-resolution parameters.
=> add support for 25km

src/glacier.c
Removed second multiplication by `veg_con[iveg].Cv` in glacier.c, line #84
This addresses issue #888
=> Unit conversion bug in Support/vic.4.2.glacier

.travis.yml, vic/drivers/python/setup.py
default behavior is unchanged, but fixes builds on e.g. conda where compilers have funky names (https://github.com/conda-forge/vic-feedstock/pull/4) or `gcc` is not what should be used.
I ran uncrustify but didn't commit the changes because it changed a bunch of C files that aren't related to this PR. There isn't a release notes section for the next unreleased version, so I didn't feel ready to start one with such a minor fix.
=> cffi headers: respect $CC if defined

docs/Documentation/Drivers/Image/ImageDriver.md
Changing image driver documentation of evaluation order from `time-before-space` to `space-before-time` based on  Hamman et al. 2018.
=> update image driver documentation
