UW-Hydro/VIC

drivers/image/src/vic_force.c

Corrected indexing (vidx) not (v) and moved within check for vidx != -1

Fixed indexing for veg_hist averages.

---

CONTRIBUTING.md

A link to this document will show up when creating new issues and pull requests.

Add contributing guidelines to repo

---

.travis.yml
vic/drivers/cesm/Makefile
vic/drivers/cesm/include/vic_driver_cesm.h

@bartnijssen - can you tell why this failing? It is working for me locally w/o any errors.
https://travis-ci.org/jhamman/VIC/jobs/74324104#L511

add travis build for cesm shared object test makefile

---

docs/Overview/ModelOverview.md

just a few fixes to captions and references.
built locally, everything looks good.

fixing up #258

---

vic/drivers/python/vic_headers.py
vic/drivers/shared/include/vic_driver_shared.h
vic/vic_run/include/vic_run.h

this function doesn't exist in any of the source files.

remove unused declarations

---

vic/drivers/cesm/cpl_mct/lnd_comp_mct.F90

update iulog and shrlogunit implementation, update subname and write statements, add notes for nextsw_cday usage.

lnd_comp_mct code review and some minor changes

---

vic/drivers/image/src/get_nc_dimension.c
vic/drivers/image/src/get_nc_field.c
vic/drivers/image/src/put_nc_field.c
vic/drivers/image/src/vic_finalize.c
vic/drivers/image/src/vic_init_output.c
vic/drivers/image/src/vic_store.c
vic/vic_run/include/vic_log.h

fixes #277.  This will greatly improve debugging related to netCDF I/O.

Remove log_ncerr

---

docs/Development/ReleaseNotes.md
docs/Documentation/Drivers/Classic/GlobalParam.md
vic/drivers/classic/src/display_current_settings.c
vic/drivers/classic/src/get_global_param.c
vic/drivers/image/src/display_current_settings.c
vic/drivers/image/src/get_global_param.c
vic/drivers/image/src/vic_mpi_support.c
vic/drivers/python/src/display_current_settings.c
vic/drivers/python/vic_headers.py
vic/drivers/shared/src/initialize_global.c
vic/drivers/shared/src/print_library_shared.c
vic/vic_run/include/vic_def.h

remove unused measure_h

---

tests/unit/shared/test_vic_time.py
vic/drivers/shared/src/vic_time.c

fix rounding / precision bug at midnight with subdaily timestep

---

src/full_energy.c
src/read_lakeparam.c

Fix to calculation of OUT_PREC for output files when LAKES=TRUE.

---

src/full_energy.c
src/initialize_atmos.c
src/read_vegparam.c
src/vicNl.c
src/vicNl.h
src/vicNl_def.h

Fix to overwriting of veg_lib with cell-specific values.

---

docs/Development/ReleaseNotes.md
tests/unit/shared/test_vic_time.py
vic/drivers/shared/src/vic_time.c

fixes #312 
cc @wietsefranssen

fix time units

---

vic/drivers/shared/include/vic_driver_shared.h

Replaced hardcoded string sizes by MAXSTRING

---

vic/drivers/classic/src/alloc_atmos.c

Removed extra allocations of carbon and lake input vars.

---

vic/drivers/shared/src/cmd_proc.c

update compile time options usage line

---

vic/drivers/classic/src/alloc_atmos.c
vic/drivers/classic/src/read_soilparam.c
vic/drivers/python/vic_headers.py
vic/vic_run/include/vic_run.h
vic/vic_run/src/runoff.c
vic/vic_run/src/surface_fluxes.c

Fix wb errs

---

vic/drivers/classic/src/alloc_atmos.c
vic/drivers/classic/src/read_soilparam.c
vic/drivers/python/vic_headers.py
vic/drivers/shared/src/make_dmy.c
vic/vic_run/include/vic_run.h
vic/vic_run/src/runoff.c
vic/vic_run/src/surface_fluxes.c

This addresses issue #343.
Only 1 file was changed: make_dmy.c.  The other changes here are from other branches that are in various stages of being pulled/merged.

Fix forceskip

---

docs/Development/CompatOpt.md
docs/Development/CurrentVersion.md
docs/Development/VersionSummaries.md

Update 4.2 docs to include descriptions of releases 4.2.a-4.2.c.

---

vic/drivers/classic/src/vic_force.c
vic/drivers/image/src/vic_force.c

Fixed typos in log_warn() calls.

---

docs/Documentation/Drivers/Image/Params.md

There is a lot more work to do on these docs but this outlines how to use existing tools for creating VIC 5 parameters for image mode.
cc @tbohn: give these a try and we can work to make them more user friendly.

add initial docs for 4 to 5 conversion

---

docs/Documentation/Drivers/Classic/GlobalParam.md
docs/Documentation/Drivers/Classic/OutputFormatting.md
samples/global.param.sample.classic.txt
samples/global.param.sample.image.txt
vic/drivers/classic/include/vic_driver_classic.h
vic/drivers/classic/src/get_force_type.c
vic/drivers/classic/src/get_global_param.c
vic/drivers/classic/src/parse_output_info.c
vic/drivers/image/src/get_global_param.c

remove duplicate dimension info from global parameter file, fixes #366

---

tests/unit/shared/test_vic_time.py

fix failing unit tests in test_vic_time.py

---

vic/drivers/shared_image/src/get_nc_var_attr.c

@jhamman: I think this is the fix that is needed. This is just for review
Let me know how to squash all these "merge" commits.

Commit to fix memory error in get_nc_var_text

---

vic/drivers/cesm/bld/vic.inputfiles.cfg
vic/drivers/cesm/src/vic_force.c
vic/drivers/classic/src/read_vegparam.c
vic/drivers/image/src/vic_force.c
vic/drivers/shared_all/src/print_library_shared.c
vic/drivers/shared_all/src/put_data.c
vic/drivers/shared_image/src/get_global_domain.c
vic/drivers/shared_image/src/init_library.c
vic/drivers/shared_image/src/vic_init.c
vic/vic_run/include/vic_def.h

I'm going to do a full refactor of `vic_init.c` this weekend and the changes shown below are just a temporary fix. The rest of the changes in this PR are specific to the CESM driver.

minor fixes while debugging CESM driver

---

tests/examples/global_param.image.STEHE.feb.txt

This should fix the failing test in the image driver in #425 ([build](https://travis-ci.org/UW-Hydro/VIC/builds/119341164)).

update path to stehekin image params

---

vic/drivers/shared_image/src/vic_init.c

Fixed typo in vic_init() that prevented Pfactor from being read.

---

vic/drivers/shared_image/src/get_global_domain.c
vic/drivers/shared_image/src/vic_init_output.c

The locations from 1d latlon input where incorrectly retrieved. This is fixed now.
unluckily with an ugly uncrustify ;)

fixed retreiving incorrect global_domain locations for 1d input grid

---

vic/vic_run/src/lakes.eb.c

always calculate windi in lakes.eb.c

---

src/read_vegparam.c

Hi Joe and Ted, 
This pull request is for #455.
Cheers!
Bin.

Fix the bug of  #455

---

docs/Datasets/Datasets.md
docs/Documentation/Drivers/CESM/CESMDriver.md
docs/Documentation/Drivers/CESM/Inputs.md
docs/Documentation/UserGuide.md
docs/Overview/ModelOverview.md

doc updates, mostly for CESM driver

---

docs/Development/Testing.md
tests/README.md

update test suite docs

---

docs/Development/ReleaseNotes.md
docs/Documentation/Drivers/Classic/Inputs.md

Two outstanding issues that should be handled in subsequent PRs.
- #79 - test datasets
- #18 - classic driver forcing file metadata

update release notes for 5.0

---

vic/drivers/classic/src/vic_force.c
vic/drivers/image/src/vic_force.c
vic/drivers/shared_all/src/forcing_utils.c

- Keeping the air pressure in Pa (as it is read in)
- Also fixed some comments related to unit description

Fixed forcing unit conversion bug in image driver

---

vic/vic_run/src/vic_run.c

Fixed call to water_balance() in vic_run().

---

vic/drivers/image/src/vic_image_finalize.c
vic/drivers/shared_all/src/print_library_shared.c
vic/drivers/shared_image/src/vic_init.c
vic/drivers/shared_image/src/vic_start.c
vic/vic_run/src/vic_run.c

Fixed some bugs
* Some fixes are related to assuring that image driver has the same behavior as classic driver

Fixed some bugs - related to assuring that image driver has the same behavior as classic driver

---

.travis.yml
vic/drivers/classic/src/read_initial_model_state.c
vic/drivers/shared_all/src/compute_derived_state_vars.c
vic/vic_run/src/calc_surf_energy_bal.c
vic/vic_run/src/snow_utility.c
vic/vic_run/src/solve_snow.c

Fixed a unit conversion bug in vic_run, related to calculating snow depth from snow density and SWE

Fixed a unit conversion bug - snow depth, density and SWE

---

docs/Development/ModelDevelopment.md
docs/Documentation/Constants.md
docs/Documentation/Definitions.md
docs/Documentation/Drivers/Classic/SnowBandOutputFiles.md
docs/Documentation/Drivers/Classic/SnowOutputFile.md
docs/Documentation/Drivers/Classic/SoilParam.md
docs/Documentation/HowToAddNewOutputVars.md
docs/Documentation/OutputVarList.md
docs/Documentation/References.md
docs/FAQ/FAQ.md
readme.md
vic/drivers/python/setup.py

update docs for VIC 5.0

---

vic/drivers/shared_all/src/open_file.c
vic/drivers/shared_image/include/vic_driver_shared_image.h
vic/drivers/shared_image/src/check_domain_info.c
vic/drivers/shared_image/src/get_global_domain.c
vic/drivers/shared_image/src/vic_init.c
vic/drivers/shared_image/src/vic_start.c

Check that the domain information in the parameters file matches the global domain info

---

vic/drivers/image/Makefile

fixed hardcoded mpi path in Makefile

fixed hardcoded mpi path in Makefile

---

vic/drivers/shared_all/src/forcing_utils.c

Fixed bug in air density calculation

Fix bug in air density calculation

---

vic/drivers/classic/src/vic_classic_timing.c
vic/drivers/image/src/vic_image.c
vic/drivers/shared_image/src/vic_image_timing.c

just a few cleanup items, I missed a uncrustify run on a few recent prs.

run uncrustify on all sources, fix some formating in timers

---

docs/Documentation/Drivers/Image/ForcingData.md

added documentation for image driver forcing file

---

.github.com/CONTRIBUTING.md
.github.com/ISSUE_TEMPLATE.md
.github.com/PULL_REQUEST_TEMPLATE.md
readme.md

this will help new contributors provide useful comments in their issues/PRs.
xref: https://github.com/blog/2111-issue-and-pull-request-templates

Add templates for github issues and pull requests

---

docs/Documentation/Drivers/Image/Params.md

Fixed a link to the parameter conversion notebook in the image driver documentation.

Fixed a broken link in image driver documentation

---

docs/FAQ/FAQ.md

based on conversation with @bartnijssen and @yixinmao Aug. 29, 2016.
xref: #608

add faq about VIC timestep scheme

---

tests/run_profiling.py
tests/run_tests.py
tests/test_image_driver.py
tests/test_restart.py
tests/test_utils.py

These are mostly pep8 issues from your recent additions.
cc @dgergel and @yixinmao

style and formatting fixes for test suite

---

docs/Development/ReleaseNotes.md
vic/drivers/python/setup.py
vic/drivers/shared_all/include/vic_version.h

sync develop and master branches, reset version strings after 5.0.0 release

---

docs/Documentation/Drivers/Classic/RunVIC.md
docs/Documentation/Drivers/Image/RunVIC.md

clarify command line usage of stand alone VIC drivers.

update command line usage docs

---

docs/Development/ReleaseNotes.md
vic/drivers/shared_image/src/vic_init_output.c

Fixed image driver history file name timetamp - now is timstep-beginning

Fixed image driver history file name

---

docs/Development/ReleaseNotes.md
vic/drivers/cesm/src/cesm_interface_c.c
vic/drivers/cesm/src/cesm_put_data.c
vic/drivers/cesm/src/get_global_param.c
vic/drivers/cesm/src/vic_cesm_start.c
vic/drivers/cesm/src/vic_force.c
vic/drivers/shared_image/src/vic_store.c
vic/drivers/shared_image/src/vic_write.c
vic/vic_run/include/vic_def.h
vic/vic_run/include/vic_run.h
vic/vic_run/src/runoff.c

Reverts UW-Hydro/VIC#677
This commit is to revert PR #677 that mistakenly merged the develop branch into master branch right after release 5.0.1.

Revert "Merge VIC5.0.1 release into develop branch"

---

docs/Development/ReleaseNotes.md
vic/drivers/cesm/src/vic_cesm_time.c

- closes #700 
- fixes Julian day in CESM driver (was previously not being set correctly for the first time step)

fix julian day in dmy struct for first time step in CESM driver

---

tests/run_profiling.py

This PR adds run profiling for Gordon, one of the DoD machines. 
I will add run profiling figures after completion of the runs.

add section for run profiling for Gordon

---

vic/vic_run/src/CalcBlowingSnow.c
vic/vic_run/src/func_canopy_energy_bal.c
vic/vic_run/src/snow_intercept.c

run uncrustify, no code changes

---

docs/Development/ReleaseNotes.md

fix PR links in cesm documentation

---

docs/Documentation/Definitions.md

update definitions list to include missing parameters

---

docs/Development/ReleaseNotes.md

This PR merely includes a Release Notes entry for the changes in #817

add release notes entry for bulk density comb option

---

vic/drivers/cesm/src/vic_force.c
vic/drivers/classic/src/get_force_type.c
vic/drivers/classic/src/vic_force.c
vic/drivers/image/src/vic_force.c
vic/drivers/shared_image/src/vic_init.c
vic/vic_run/src/calc_surf_energy_bal.c
vic/vic_run/src/func_canopy_energy_bal.c
vic/vic_run/src/func_surf_energy_bal.c
vic/vic_run/src/solve_snow.c
vic/vic_run/src/vic_run.c

Fixes for fcanopy/LAI/esoil logic

---

vic/drivers/classic/src/parse_output_info.c
vic/drivers/classic/src/read_soilparam.c
vic/drivers/image/src/vic_force.c
vic/drivers/shared_all/src/calc_root_fraction.c
vic/drivers/shared_image/include/vic_image_log.h
vic/drivers/shared_image/src/vic_init.c
vic/vic_run/include/vic_log.h
vic/vic_run/include/vic_run.h
vic/vic_run/src/CalcBlowingSnow.c
vic/vic_run/src/vic_run.c

This is just a quick PR for updating the current `develop` branch formatting - `uncrustify` was showing a lot of changes for files not part of some of my recent PRs so I thought it was about time for one of these.

uncrustify fixes
